version: '3.7'
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: counter_service
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - counter-network

  backend:
    container_name: counter-service
    build:
      dockerfile: Dockerfile
    image: counter-service:latest
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/counter_service?serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "test"
      SPRING_DATASOURCE_PASSWORD: "test"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - counter-network

networks:
  counter-network:
    driver: bridge
    name: counter-network